import { Head, Html, NextScript } from "next/document";

export default function Document() {
  return (
    <Html data-theme="winter">
      <Head>
        <title>Notes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <main>
          <NextScript />
        </main>
      </body>
    </Html>
  );
}
